version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.15
executors:
  build_environment:
    docker:
      - image: circleci/buildpack-deps:buster

jobs:
  build:
    executor:
      name: build_environment
      steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Image
          command: |
              docker build -t somleng/somleng-freeswitch .

      - run:
          name: Check Version
          command: |
              docker run --rm somleng/somleng-freeswitch /usr/bin/freeswitch -version

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: Somleng
