version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.15
executors:
  build_environment:
    docker:
      - image: circleci/buildpack-deps:buster

jobs:
  build:
    executor:
      name: build_environment

    working_directory: ~/build_freeswitch

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Image
          command: |
              docker build -t somleng/somleng-freeswitch .

      - run:
          name: Check Version
          command: |
              docker run --rm somleng/somleng-freeswitch /usr/bin/freeswitch -version

      - run:
          name: Push Image
          command: |
              if [ "$CIRCLE_BRANCH" = "upgrade_freeswitch" ]; then
                  echo "HERE"
                  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
                  docker build -t somleng/somleng-freeswitch:latest "$CIRCLE_REPOSITORY_URL#$CIRCLE_BRANCH"
              fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: Somleng
