on:
  push:
    branches:
      - master

name: Deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
      APP_IDENTIFIER: somleng-freeswitch
      ECR_PUBLIC_REGISTRY: public.ecr.aws
      APP_ECR_REPOSITORY_URI: public.ecr.aws/somleng/somleng-freeswitch

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: aws-login
        uses: aws-actions/configure-aws-credentials@v1.5.9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          aws-region: ap-southeast-1

      - name: Login to AWS Public ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ECR_PUBLIC_REGISTRY }}
          username: ${{ env.AWS_ACCESS_KEY_ID }}
          password: ${{ env.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.APP_IDENTIFIER }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.APP_IDENTIFIER }}-

      - name: Build and push to AWS ECR `${{ env.APP_IDENTIFIER }}`
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache/.buildx-cache-${{ env.APP_IDENTIFIER }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ env.APP_IDENTIFIER }}
          tags: |
            ${{ env.APP_ECR_REPOSITORY_URI }}:latest
            ${{ env.APP_ECR_REPOSITORY_URI }}:${{ env.IMAGE_TAG  }}

      - name: Move docker layer caches
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache
          mkdir /tmp/.buildx-cache
          mv /tmp/.buildx-cache-${{ env.APP_IDENTIFIER }} /tmp/.buildx-cache

      - name: Prepare task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: deploy/production/appserver_task_definition.json
          container-name: ${{ env.APP_IDENTIFIER }}
          image: ${{ env.APP_ECR_REPOSITORY_URI }}:${{ env.IMAGE_TAG }}

      - name: Deploy App
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.APP_IDENTIFIER }}
          cluster: somleng
          wait-for-service-stability: true
