on:
  push:
    branches:
      - push_public_image

name: Deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        id: aws-login
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          aws-region: ap-southeast-1

      - name: Build Docker Image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.ap-southeast-1.amazonaws.com
          ECR_PUBLIC_REGISTRY: public.ecr.aws/somleng
          ECR_REPOSITORY: somleng-freeswitch
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_PUBLIC_REGISTRY/$ECR_REPOSITORY:latest .
          echo "::set-output name=private-image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "::set-output name=public-image::$ECR_PUBLIC_REGISTRY/$ECR_REPOSITORY:latest"

      - name: Login to Amazon ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Push Image to Amazon ECR
        env:
          PRIVATE_IMAGE: ${{ steps.build-image.outputs.private-image }}
        run: |
          docker push $PRIVATE_IMAGE

      - name: Prepare task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: deploy/production/appserver_task_definition.json
          container-name: somleng-freeswitch
          image: ${{ steps.build-image.outputs.private-image }}

      - name: Deploy App
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: somleng-freeswitch
          cluster: somleng
          wait-for-service-stability: true
